"""followers

Revision ID: 77260b30f441
Revises: 82911b442d33
Create Date: 2023-04-05 23:26:13.369948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77260b30f441'
down_revision = '82911b442d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
